
#开发环境配置
server:
  port: 8181
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    min-spare-threads: 30

#日志配置
logging:
  level:
    com.jomn: debug
    org.springframework: warn
#spring配置
spring:

  profiles:
    active: druid
  #服务模块
  devtools:
    restart:
      enabled: true
  redis:
    host: 192.168.137.85
    port: 6379
    password:
    timeout: 10000
    jedis:
      pool:
        max-active: 8
        max-wait: -1

#mybatis
mybatis:
  mapperLocations: classpath*:mapper/*Mapper.xml
  configLocation: classpath:config/mybatis-config.xml

#pageHelper分页插件
pagehelper:
  helperDialect: mysql
  resonable: true
  supporMethodArguments: true
  params: count=countSql

#shiro配置
shiro:
  user:
   loginUrl: /login
   unauthorizedUrl: /unauth
   indexUrl: /index
   captchEnabled: true
   captchType: char
  cookie:
    domain:
    path: /
    httpOnly: true
    maxAge: 30
  session:
    # Session超时时间，-1代表永不过期（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
    # 同一个用户最大会话数，比如2的意思是同一个账号允许最多同时两个人登录（默认-1不限制）
    maxSession: -1
    # 踢出之前登录的/之后登录的用户，默认踢出之前登录的用户
    kickoutAfter: false

#redis配置


















